add cleanup at start

diff --git a/.github/workflows/ci-dgraph-load-tests.yml b/.github/workflows/ci-dgraph-load-tests.yml
--- a/.github/workflows/ci-dgraph-load-tests.yml
+++ b/.github/workflows/ci-dgraph-load-tests.yml
@@ -12,6 +12,9 @@ jobs:
   dgraph-load-tests:
     runs-on: self-hosted
     steps:
+      #TODO: WE NEED TO REMOVE THIS CLEANUP, and handle it more elegantly, it makes us incompatible with gh-hosted-runners
+      - name: Cleaning Up $GITHUB_WORKSPACE
+        run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
       - uses: actions/checkout@v3
       - name: Set up Go
         uses: actions/setup-go@v3
@@ -63,6 +66,3 @@ jobs:
           ./t --suite=load
           # clean up docker containers after test execution
           ./t -r
-      - name: Cleaning Up $GITHUB_WORKSPACE
-        # Volume auto mounted by gh actions pointing to the current working-directory
-        run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
