fix(test) add cleanup at start (#8307)
* add cleanup at start

* bring in changes from https://github.com/dgraph-io/dgraph/pull/8301

* cleanup

diff --git a/.github/workflows/ci-dgraph-load-tests.yml b/.github/workflows/ci-dgraph-load-tests.yml
--- a/.github/workflows/ci-dgraph-load-tests.yml
+++ b/.github/workflows/ci-dgraph-load-tests.yml
@@ -9,6 +9,14 @@ on:
   schedule:
     - cron: "*/30 * * * *"
 jobs:
+  #TODO: WE NEED TO REMOVE THIS CLEANUP, and handle it more elegantly, it makes us incompatible with gh-hosted-runners
+  cleanup:
+    runs-on: self-hosted
+    container:
+      image: ubuntu:latest
+    steps:
+      - name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
+        run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
   dgraph-load-tests:
     runs-on: self-hosted
     steps:
@@ -63,6 +71,3 @@ jobs:
           ./t --suite=load
           # clean up docker containers after test execution
           ./t -r
-      - name: Cleaning Up $GITHUB_WORKSPACE
-        # Volume auto mounted by gh actions pointing to the current working-directory
-        run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
